CREATE DATABASE whendoodoo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE whendoodoo;

CREATE TABLE todos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  notes TEXT,
  is_done TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (session_id),
  INDEX (is_done)
);
